### ISSUE TITLE
Can't connect docker containers via Peerage.Via.Udp

### ISSUE THREAD

**Issue by dschniepp** [mrluc/peerage#10]
Today I tried to connect two docker containers via `Peerage.Via.Udp` like you mentioned in http://blog.maketogether.com/connecting-elixir-containers-with-dns-based-discovery/. But I can't get it to work. Would be awesome if you can take a look at https://github.com/dschniepp/peerage-test and tell me what am I missing. Every two seconds my program is printing the node list via `Node.list()` but it's empty. Thank you very much!

**Comment by mrluc** [comment]
I can't check this out until a bit later -- but in case it's helpful:

- I tested that via running "docker run" two times on the same machine, so using host networking by default, and I think I mentioned that the default behavior (at least at the time of writing) is that UDP multicast is permitted. That will of course depend on if it's permitted on your machine/network.

- However, docker-compose may be a different story! It sets up [its own networking](https://docs.docker.com/compose/networking/), and I don't know if OOTB it is broadcast friendly. See [this suggestion](https://stackoverflow.com/questions/42422406/receive-udp-multicast-in-docker-container) which may be what you're looking for, if the reason you're using Docker is as a lightweight way to easily test clustered, built elixir releases in local development.

- When it comes time to deploy, what would be the 'Docker Stack' way of setting up this kind of service discovery? Probably Swarm, where [you can set RR service discovery](https://docs.docker.com/engine/swarm/networking/#configure-service-discovery) to get the same kind of DNS-based "one name, list of IPs" behavior that k8s, Weave, etc also support.

I've been using minikube locally, which is nice because it's closer to 1:1 w/deploys, and even though it's a single machine, it's using the same overlay network/dns-based discovery.

**Comment by dschniepp** [comment]
Thank you for your quick reply I will give a try. 

Currently we deploy our apps via AWS ElasticBeanstalk. I heard of minikube but we haven't use k8s yet.

**Comment by ksheurs** [comment]
@dschniepp ever have any success with this? looking to do a similar setup (multiple docker apps on eb). thank you!

**Comment by ksheurs** [comment]
Ok, working locally with 2 running Docker containers I am able to get some discovery going with the Udp provider:

```shell
[debug]   -> Peerage.Via.Udp sees: node1@8a70db78d1e8
[debug]   -> Peerage.Via.Udp sees: node2@97f533270bfc
[debug]   -> Peerage.Via.Udp sees: node2@97f533270bfc
[debug]   -> Peerage.Via.Udp sees: node1@8a70db78d1e8
[debug] [Peerage 1.0.2][ Elixir.Peerage.Via.Udp] Discovery every 10s.

     NAME                RESULT OF ATTEMPT
     node1@8a70db78d1e8  true
     node2@97f533270bfc  false

     LIVE NODES
     node1@8a70db78d1e8 (self)
```

My config is like so: `config :peerage, via: Peerage.Via.Udp, serves: true, port: 45900` and I'm running IEX like so:

```shell
docker run -it --rm api iex --sname node1 -S mix
docker run -it --rm api iex --sname node1 -S mix
```

It seems the attempt or a `Node.ping :"node2@97f533270bfc"` fails. Is there any other config necessary for a Phoenix app running on Docker on Mac?

**Comment by ksheurs** [comment]
By the way, the Docker containers are sharing the same network in bridge mode.

**Comment by mrluc** [comment]
@ksheurs Mmm, that's interesting -- so at least we can say 2 things:

1. UDP multicast is working for you; the containers are able to communicate their node names to each other.
2. `Node.connect` or `Node.ping` is not working; it's being given the node name, but it can't do anything with it.

That makes me wonder about DNS. Launching the node with `sname` appears to result in an interesting host name; I wonder if `nslookup 97f533270bfc` from within the container would work, either? That's all the info the erlang stdlib has to go on when trying to answer the question "where is the node that has this name?"

Depending on guarantees about hostname at container startup time, it might be possible to use `--name` instead of `--sname` in your 'runner' image, to provide the hostname yourself. You could look up the hostname in the runner image's startup, and splice it into the `--name`. The basic question is whether or not your containers can reach each other by default with your non-host networking, or if some additional (non-elixir) config is needed to let these containers resolve each others' names and connect to each other. 

Then, once confirmed that the containers can 'see' and ping each other, there are questions about your app's config, the container config, and also your orchestrator's config if you're using one. For instance

- the app's config will usually want to constrain the erlang distribution ports to a more limited range
- the dockerfile for the container should expose the erlang distribution ports
- and the then at the orchestrator level again this is usually necessary and will vary based on orchestrator (eg, k8s vs docker-compose have different ways of saying 'these services/headless services/group of containers all have this port open'...).

**Comment by ksheurs** [comment]
Thanks so much for the detailed reply @mrluc!

Running `nslookup` on one of the instances for both self and the other node:

```shell
root@2ac1934e72be: nslookup 2ac1934e72be
Server:		192.168.65.1
Address:	192.168.65.1#53
** server can't find 2ac1934e72be: NXDOMAIN

root@2ac1934e72be: nslookup 29e3f9d21b4e
Server:		192.168.65.1
Address:	192.168.65.1#53
** server can't find 29e3f9d21b4e: NXDOMAIN
```

If I `docker ps` and then inspect each of the running containers and get their IPAddress's, I can successfully `ping {ip}` both from one of the containers. So, I think that's a good sign! Is this possibly just an issue with the container hostname's that are being set (2ac1934e72be and 29e3f9d21b4e)?

If using `--name` is the way to go, I think I'll need some more detail on how look this value up. Thanks again!

**Comment by ksheurs** [comment]
If helpful, this is what `/etc/hosts` looks like on one of the instances:

```
root@ 2ac1934e72be:/app# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	2ac1934e72be
```

**Comment by ksheurs** [comment]
Resolved! I needed to include `--net={my-bridge-network}` in the `docker run` calls! Thanks again.

**Comment by mrluc** [comment]
@ksheurs Looking up the container's IP is something that varies based on your container and env it runs in; worst comes to worst there'll usually be a way to extract it from `dig` or `nslookup`, or pull it out of /etc/hosts as you mention.

You may also already be getting it the container's IP in an env var -- several orchestrators support that. Kubernetes ('downward api') and Convox do this; I don't know if Docker does nowadays (Docker does have more orchestration/networking pieces than it used to).

Fwiw, that last entry in the /etc/hosts file looks the most promising, as it seems to match up with the auto-generated hostname. If you can automate pulling that from eg. dig or nslookup into an env var, that's probably enough to make a good --name.

At that point the node can attempt to reach its fellows -- via erlang distribution, whose ports may be the next thing that needs configured in the container and/or in the app.

Edit: oh, that's great news! Glad to hear it.

**Comment by dschniepp** [comment]
@ksheurs I switched to libcluster and implemented a custom ec2 strategy because aws does not support udp and eb doesn't support bridge-networks either.

**Comment by ksheurs** [comment]
Thanks @dschniepp - I'll check that out today.

**Comment by dschniepp** [comment]
@ksheurs you can take a look at https://github.com/kyleaa/libcluster-elasticbeanstalk

**Comment by mrluc** [comment]
Oh, sweet, I hadn't seen https://github.com/kyleaa/libcluster_ec2 -- would be cool to do a PR w/a peerage Provider, might be pretty straightforward.

**Comment by ksheurs** [comment]
So, before looking at libcluster, I've written an Ec2 provider for Peerage. It correctly polls for all active instances/hostnames, but I cannot seem to connect/ping between nodes (receiving a `:pang`). I wonder if this is what @dschniepp was saying re: bridge networks? I looked into it a bit more and seems ECS [supports this now](https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-service-now-supports-networking-modes-and-memory-reservation/) (which I imagine EB uses under the hood for Docker (?). I wonder if I need to be in host network mode.

Any other ideas would be appreciated! @mrluc if this works out, I'll do a PR for the Ec2 provider!

**Comment by ksheurs** [comment]
Btw, doing a `eb ssh` and then `docker inspect` on the running instance it seems it's def defaulting to bridge networking mode: https://cl.ly/2p0F0H3n0d30.

**Comment by dschniepp** [comment]
Is this your AWS CF file? I published our Multi-Docker-EB Dockerrun.aws.json https://gist.github.com/dschniepp/61aba22b720e546b880a84c6f2d05aa2 these ports needs to be open if you set the vm.args like this `-kernel inet_dist_listen_min 9100 inet_dist_listen_max 9100`. Further more the security group of ec2 instances must allow private network traffic on these ports.

**Comment by ksheurs** [comment]
mmm nice, ok i'll open those ports in my Dockerrun.aws.json! i was only exposing then in the Dockerfile. the screenshot i shared was from running `docker inspect {container-id}` on the ec2 instance.

**Comment by dschniepp** [comment]
@ksheurs do you have a demo repo where i can take a look at it?

**Comment by ksheurs** [comment]
Thanks for the offer, @dschniepp. Currently it's an internal repo, but let me try a few more things and if no go, I'll make up a test case repo for us both to look at. Thanks again.

**Comment by ksheurs** [comment]
I got this working, @dschniepp! I think it was a combo of opening up the ports in both my Dockerfile and Dockerrun.aws.json + properly templating my `--name node@host` on app startup. To do the latter I used the following which is within my Docker `CMD` script:

```bash
export NODE_HOST=$(curl -s -S http://169.254.169.254/latest/meta-data/local-ipv4)
--name node@$NODE_HOST
```

Feel free to close @mrluc!

**Comment by mrluc** [comment]
+1.
