### ISSUE TITLE
DNS GenServer

### ISSUE THREAD

**Issue by ksheurs** [mrluc/peerage#11]
I noticed the UDP provider is built as a GenServer, but not the DNS one. I'm newer to Elixir, but could you explain why this is the case?

**Comment by mrluc** [comment]
The reason is hinted at in the end of the Readme, [where it mentions custom providers:](https://github.com/mrluc/peerage#custom-providers):

> For simple cases, where you're polling a source of truth (some API, etc): just provide a poll method ...
> For more complex, peer-to-peer cases -- say, UDP multicast, where each node is broadcasting itself on the network -- you'll probably want to use a GenServer, listening for incoming broadcast messages, and building up a list of 'seen' nodes over time.

The providers that just poll a source of truth are all pretty straightforward, and can be stateless. (Peerage.Server is stateful, but all it does is keep a set of node names, call `MyProvider.poll()` to get the latest known, and connect to any new ones).

However, with p2p, there's nothing that MyProvider can do to find a list of all known nodes 'on demand'; it's growing a list of known nodes over time, by listening for their broadcasts (which there are less chatty ways of doing, not that that's an important optimization with the rough limits on cluster size we have). So Peerage.Server will call the MyProvider's poll(), but MyProvider necessarily must be or make use of a stateful actor, with a built-up list ready to return, which means that in those cases `MyProvider.poll()` will probably be a client function of a GenServer.

We can even take care of running MyProvider's server, with the `serves: true` config flag. They don't have to make use of that capability if they don't want to; their `poll()` client method could obviously be calling anywhere, including into a GenServer they're running in their own app's supervision tree.

**Comment by mrluc** [comment]
So `Peerage.Via.Dns` is basically polling a source of truth (port 53).

**Comment by ksheurs** [comment]
Thanks very much @mrluc. This was helpful!
