### ISSUE TITLE
DNS provider on AWS

### ISSUE THREAD

**Issue by ksheurs** [mrluc/peerage#12]
Hi @mrluc. I've successfully gotten a workflow working in development with Docker and the UDP provider. Thanks for your help on that.

I'm now trying the DNS provider in my staging environment on AWS (ElasticBeanstalk) and I am seeing the following errors in my log:

```log
04:16:37.195 [error] ** System NOT running to use fully qualified hostnames **
** Hostname {correct-node-ip-address} is illegal **
```

It seems to correctly poll/query for IP addresses, but I imagine my configuration around ports or sname is wrong. Some information about my configuration:

Elixir config:
```elixir
config :peerage, via: Peerage.Via.Dns, app_name: "myapp", dns_name: "myapp.privatezone.internal"
```

Docker config:
```docker
EXPOSE 4000 # port the app is running on

CMD elixir --erl '-kernel inet_dist_listen_min 9000' --erl '-kernel inet_dist_listen_max 9010' --sname myapp --cookie mycookie -S mix phx.server
```

AWS security group config: https://cl.ly/1f3P2l3m123c

Do I need to EXPOSE additional ports in Docker? If so, why does it work in development without doing that? Does the security group config look OK and is that necessary? Anything else I might be missing would be appreciated!

**Comment by mrluc** [comment]
All of the above, I would guess, but that might not be the most pressing issue.

- **exposing ports:** yes, local docker is a lot more permissive wrt traffic between containers than deployment envs will be. It is probably correct to open 4369, and all of the ports opened in dist_listen_min etc, in the DockerFile. You can actually trim dist_listen_min/max down to a single port I believe, with no issues.

- **node name:** nodes can't have the same name; this container config will make each container have the same short name. It will always be necessary to template the node name, because if two erlang nodes have the same name, how can we expect them to resolve to different network locations? :) More specifically, `--sname` is a bad fit for Dns-based discovery, because Dns-based service discovery by definition resolves names to IPs, which it combines with the app's name to form a node name that can be resolved, like: `myapp@1.1.1.1`.

However, the bigger question is:

**What service discovery is even available to you on Elastic Beanstalk?** 

Is dns-based service discovery even provided? Ie, does EB have an arrangement so that, when you deploy app 'foo', `nslookup foo` from within the container will return a list of all other foo container IPs?

There I don't know; I think the answer might be no -- I use k8s, and have used convox with the Weave AMI in the past, but I haven't used EB seriously in years, so I don't know if there's any kind of service discovery built in now. I think the answer to that kind of thing in the past has been "use CF with ECS to manage Route 53 records," aka, roll your own service discovery -- and I think that maybe the lack of that sort of thing in the Amazon ecosystem is why the Weave ECS AMI existed in the first place.

(If it's possible to do EB service discovery out of the box, that would be a really valuable contribution waiting to happen, maybe as a separate Provider library).

**Comment by ksheurs** [comment]
Cool, I will try exposing those ports now. Re: `--sname`, in development over Udp I was able to see and ping multiple nodes with the same sname (each with a different host). I had assumed the overall "name@host" needed to be unique (vs just the name). 

So, Route 53 offers private zones which I think can be used for discovery. Currently for my test I have service1 and service2. Each has a private DNS entry for service1.company.internal and service2.company.internal. Configs for peerage would be `via: Peerage.Via.Dns, app_name: "service1", dns_name: "service1.company.internal"` and `via: Peerage.Via.Dns, app_name: "service2", dns_name: "service2.company.internal"`. Calling `nslookup service1.company.internal` indeed reveals all the IP's behind that service:

```bash
[ec2-user@ip-172-31-48-183 ~]$ nslookup service1.company.internal
Server:		172.31.0.2
Address:	172.31.0.2#53

Non-authoritative answer:
service1.company.internal	canonical name = service1-staging.us-east-1.elasticbeanstalk.com.
Name:	service1-staging.us-east-1.elasticbeanstalk.com
Address: 34.200.53.108
Name:	service1-staging.us-east-1.elasticbeanstalk.com
Address: 54.173.36.54
```

My targets would be those two addresses at the end. If I find an extra provider is needed - I will definitely contribute something upstream!

**Comment by mrluc** [comment]
Oh, sounds great. (Also, maybe I should use EB more). 

Yeah, I think all you need is to template the node name then!

**Comment by ksheurs** [comment]
With the port adjustments and running just a single instance (figured I won't run into multiple sname issues for the time being) I am still receiving the following:

```log
22:26:54.313 [error] ** System NOT running to use fully qualified hostnames **
** Hostname {ip-address} is illegal **
```

Anything else you can think of specific to this error? Thanks again.

**Comment by mrluc** [comment]
[That might be sname related](http://erlang.org/pipermail/erlang-questions/2011-June/059141.html); I think it doesn't like being given a fqdn when it's initialized for shortnames.

**Comment by ksheurs** [comment]
Thanks @mrluc - very helpful. I'll give this a try now. I think I was also mistaken re: the Route53 provider. The `nslookup` only returns the ELB IP's, not the IP's of the instances behind it. I think a custom provider polling the AWS EC2 API might be needed here.

**Comment by mrluc** [comment]
I think you're right.

A provider could probably be based on [ExAws.EC2.describe_instances/1](https://hexdocs.pm/ex_aws/ExAws.EC2.html#describe_instances/1), which wouldn't need to be very complex (just a `poll` function) as it'd be polling a source of truth, not building up state.

**Comment by mrluc** [comment]
Older issue -- but closing now because it looks like there's an option on AWS now where DNS discovery should work ootb: https://aws.amazon.com/fargate/, which looks cool!
